version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "3000"
    networks:
      - coffee-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "5001"
    env_file:
      - server/src/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coffee-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./nginx/nginx.key:/etc/ssl/private/nginx.key
    depends_on:
      - frontend
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge